server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://localhost:3306/user_service"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pbhyclls
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signerKey: 2c5dfe83271d0b206b1d4e226a3f351601b454dfb83da5465672e507ed0fabbc
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
